spring:
  application:
    name: terefas_Enos_Emanuel_RU_4729720
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3310/tarefasAtividade
    username: enos
    password: Enos!2486

server:
  port: 8080
